title: Proud to be
author: EpicPwner
email: kkatamari@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  A community based around the idea of beeing a nerd. A nerd by definition is someone who obcesses over unpopular or non-mainstream subjects, activities or hobbies.
  This concept is not exclusive for gamming additcs or D&D sessions in the mothers basement. If you identify with this mental state you'll feel just at home.

# social links

github_username:  [EpicPwner](https://github.com/EpicPwner)

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
